
#Networks
  # Todos os serviços devem usar a rede BACKEND para interagirem entre si
networks:
  mongo_network:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodb_server_data:

services:
  # MongoDB AUTH Database
  bantads_authdb:
    container_name: bantads_authdb
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: bantads
    volumes:
      - mongodb_server_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - mongo_network

  # API Gateway
  bantads-api-gateway:
    image: bantads-api-gateway
    container_name: bantads_api_gateway
    build:
      context: ..
      dockerfile: ./.docker/APIGateway_Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../:/usr/src/app:rw
    networks:
      - backend

  #Authentication Service
  auth-ws:
    image: auth-ws:0.0.1-SNAPSHOT
    container_name: bantads_auth-ws
    ports:
      - 8080:8080
    networks:
      - backend
      - mongo_network
    environment:
      - MONGO_HOST=bantads_authdb
    depends_on:
      - bantads_authdb






